[package]
name = "sledgehammer-bindgen"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version="1.0", features=["full", "extra-traits"] }
quote = "1.0"

[lib]
proc-macro = true
ux = "0.1.5"

[dev-dependencies]
ux = "0.1.5"
wasm-bindgen = "0.2"
rustc-hash = "1.1.0"
once_cell = "1.16.0"
lru = "0.8.1"