[package]
name = "sledgehammer-bindgen"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version="1.0", features=["full", "extra-traits"] }
quote = "1.0"

[lib]
proc-macro = true
ux = "0.1.5"

[dev-dependencies]
sledgehammer_utils = "0.1.0"
wasm-bindgen = "0.2"